spring.application.name=ListaDeSupermercado


# Configuração do banco no mySQL

# Nome do banco: db_lista_supermercado
spring.datasource.url=jdbc:mysql://localhost:3306/db_lista_supermercado?createDatabaseIfNotExist=true&serverTimezone=UTC&useSSL=false
spring.datasource.username=root
spring.datasource.password=LabProgramacao2026!!

# Driver de Conexão MySQL
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


# JPA / HIBERNATE

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Atualização automática, conforme o Model
spring.jpa.hibernate.ddl-auto=update

# Exibe as consultas SQL geradas no console para conferência
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#porta
server.port=8080
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true
